2023-04-06 10:35:33,121 (56411/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-06 10:35:33,122 (56411/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-04-06 10:38:50,840 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'create table (id serial, email varchar(200) not null, hashed_password varchar(256) not null, fullname varchar(100), scopes varchar(200) not null)', error: SyntaxError('syntax error at or near "("\nLINE 1: create table (id serial, email varchar(200) not null, hashed...\n                     ^')
2023-04-06 10:38:50,845 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "("\nLINE 1: create table (id serial, email varchar(200) not null, hashed...\n                     ^\n'
2023-04-06 10:42:49,011 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb modify column email unique', error: SyntaxError('syntax error at or near "modify"\nLINE 1: alter table user_tb modify column email unique\n                            ^')
2023-04-06 10:42:49,016 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "modify"\nLINE 1: alter table user_tb modify column email unique\n                            ^\n'
2023-04-06 10:43:12,708 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb alter column email unique', error: SyntaxError('syntax error at or near "unique"\nLINE 1: alter table user_tb alter column email unique\n                                               ^')
2023-04-06 10:43:12,710 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "unique"\nLINE 1: alter table user_tb alter column email unique\n                                               ^\n'
2023-04-06 11:53:20,105 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column role varchar(20) not null default "Normal user"', error: FeatureNotSupported('cannot use column reference in DEFAULT expression')
2023-04-06 11:53:20,109 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression\n'
2023-04-06 11:53:40,608 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column role varchar(20) not null', error: NotNullViolation('column "role" of relation "user_tb" contains null values')
2023-04-06 11:53:40,609 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.NotNullViolation: column "role" of relation "user_tb" contains null values\n'
2023-04-06 11:53:52,628 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column role varchar(20) not null default "Normal user"', error: FeatureNotSupported('cannot use column reference in DEFAULT expression')
2023-04-06 11:53:52,629 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression\n'
2023-04-06 11:56:02,492 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column role varchar(20) not null default "Normal user"', error: FeatureNotSupported('cannot use column reference in DEFAULT expression')
2023-04-06 11:56:02,498 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression\n'
2023-04-06 11:56:22,918 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column user_role varchar(20) not null default "Normal user"', error: FeatureNotSupported('cannot use column reference in DEFAULT expression')
2023-04-06 11:56:22,920 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression\n'
2023-04-06 11:57:03,033 (56411/MainThread) pgcli.pgexecute ERROR - sql: 'alter table user_tb add column user_role varchar(20) default "Normal user" not null', error: FeatureNotSupported('cannot use column reference in DEFAULT expression')
2023-04-06 11:57:03,038 (56411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression\n'
